CREATE TABLE books ()
id SERIAL PRIMARY KEY,
cover_state VARCHAR(255) NOT NULL,
publisher VARCHAR(255)

CREATE TABLE label ()
id SERIAL PRIMARY KEY,
title VARCHAR(255) NOT NULL,
color VARCHAR(255) NOT NULL
